################################################################################################
# Builder image
# See https://hub.docker.com/_/golang/
################################################################################################
FROM golang:1.24 as builder

ARG OS=linux
ARG ARCH=amd64

WORKDIR /usr/src/app

# pre-copy/cache parent go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build -v -o argocd-mcp-server main.go

################################################################################################
# image to be run by the GitHub Action job
################################################################################################
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as argocd-mcp

# Copy the generated binary into the $PATH so it can be invoked
COPY --from=builder /usr/src/app/argocd-mcp-server /usr/local/bin/

ENV ARGOCD_MCP_URL=https://argocd-server
ENV ARGOCD_MCP_TOKEN=secure-token
ENV ARGOCD_MCP_INSECURE=false
ENV ARGOCD_MCP_DEBUG=false
ENV ARGOCD_MCP_LISTEN_PORT=8080

# Run as non-root user
USER 1001

EXPOSE ${ARGOCD_MCP_LISTEN_PORT}

CMD /usr/local/bin/argocd-mcp --transport http --argocd-url $ARGOCD_MCP_URL --argocd-token $ARGOCD_MCP_TOKEN --insecure $ARGOCD_MCP_INSECURE --debug $ARGOCD_MCP_DEBUG --listen :$ARGOCD_MCP_LISTEN_PORT